# Travis-CI can't handle fancy shell syntax or some types of one-liners, so keep it simple and don't trust their lint tool to catch many problems.
language:
    - c

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

env:
    matrix:
        - QT_VERSION=qt4 QT_OPENGL_DEV_PACKAGE=libqt4-opengl-dev
        - QT_VERSION=qt5 QT_OPENGL_DEV_PACKAGE=libqt5opengl5-dev


matrix:
  exclude:
    - os: osx
      env: QT_VERSION=qt4 QT_OPENGL_DEV_PACKAGE=libqt4-opengl-dev

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi

install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ${QT_VERSION}; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install git ${QT_VERSION}-qmake ${QT_OPENGL_DEV_PACKAGE} valgrind; fi
    - git config --global user.email \<\>
    - git config --global user.name "Embroidermodder-Travis"

before_script:
    - cat /etc/lsb-release
    - uname -a

script:
    # Do only a basic build for pull requests, otherwise build for all platforms
    # - pushd ${TRAVIS_BUILD_DIR}/project-files/qmake && qmake && make && popd
    - pushd ${TRAVIS_BUILD_DIR}/libembroidery && qmake && make && popd
    - pushd ${TRAVIS_BUILD_DIR}/libembroidery-convert && qmake && make && popd
    - pushd ${TRAVIS_BUILD_DIR}/embroidermodder2 && qmake && make && popd
    - pushd ${TRAVIS_BUILD_DIR}/libembroidery-test && qmake && make && popd
    - ${TRAVIS_BUILD_DIR}/libembroidery-test/libembroidery-test

