# Travis-CI can't handle fancy shell syntax or some types of one-liners,
# so keep it simple and don't trust their lint tool to catch many problems.
language:
    - c

os:
    - linux

compiler:
    - gcc

env:
    matrix:
        - QT_VERSION=qt5 QT_OPENGL_DEV_PACKAGE=libqt5opengl5-dev

before_install:
    - sudo apt-get update -qq
    - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
    - rustup show

install:
    - sudo apt-get install git ${QT_VERSION}-qmake ${QT_OPENGL_DEV_PACKAGE} valgrind

before_script:
    - cat /etc/lsb-release
    - uname -a

script:
    - make

